### ISSUE TITLE
service_client_example.cpp callback return

### ISSUE THREAD

**Issue by HarrisonBT** [ctu-mrs/ros2_uav_example#4]
In the service client example I notice that you added a callback for the service response future.

This callback is not void, actually a boolean where a result of true or false can be returned.

My question is how does anyone invoke any action based on the return of the callback function (true or false) because it is called by the service client itself when the response future is ready. 

Thanks, 
H

**Comment by matemat13** [comment]
Hello, thank you for spotting this! It is indeed a nonsense. I've fixed this and updated the other examples to be compatible with ROS2 Galactic. These were some of our first experiments with ROS2, so some of the stuff can probably be written a bit better. I'll take some time and go through them a bit more carefully tomorrow.

**Comment by matemat13** [comment]
ok, I've made some minor cleanup and refactor and updates for Galactic, check out the examples now :)

**Comment by HarrisonBT** [comment]
Cool, I like the timer future callback idea.

I don't think your actual future callback will ever be called though, because it was not bound to the async_send_request.


Thanks,
H
